import type { AircraftDefinition } from '@/game/types.ts';

export const DEFAULT_AIRCRAFT_ID = 'storybook_biplane';

export const AIRCRAFT: AircraftDefinition[] = [
  {
    id: 'storybook_biplane',
    name: 'Sunny Biplane',
    era: 'ww1',
    displayRole: 'default',
    handlingLabel: 'Bright gentle cruiser',
    difficulty: 'gentle',
    available: true,
    modelFormat: 'obj',
    modelPath: '/assets/aircraft/low_poly_biplane/biplane.obj',
    texturePath: '/assets/aircraft/low_poly_biplane/diffuse_512.png',
    orientationPreset: 'obj-x-forward',
    scale: 1,
    targetVisualSize: 14,
    cameraSafeRadius: 11,
    modelRotationY: Math.PI / 2,
    modelRotationZ: 0,
    propellerBlur: { offset: [0, 0.08, -6.4], radius: 2.1, axis: 'z', color: 0xfff4bd, opacity: 0.34 },
    tuning: {
      minSpeed: 20,
      maxSpeed: 118,
      acceleration: 28,
      drag: 0.82,
      pitchRate: 0.82,
      rollRate: 1.02,
      yawRate: 0.76,
      liftFactor: 0.8,
      stability: 0.78,
      autoLevelStrength: 3.7,
    },
    camera: { chaseDistance: 17, chaseHeight: 6, lookAhead: 10, fov: 59 },
  },
  {
    id: 'wright_flyer',
    name: 'Sunrise Flyer',
    era: 'ww1',
    displayRole: 'default',
    handlingLabel: 'Gentle vintage lift',
    difficulty: 'gentle',
    available: false,
    modelPath: '/assets/aircraft/1903_wright_flyer/scene.gltf',
    scale: 0.1,
    targetVisualSize: 16,
    cameraSafeRadius: 12,
    modelRotationY: 0,
    tuning: {
      minSpeed: 18,
      maxSpeed: 105,
      acceleration: 24,
      drag: 0.9,
      pitchRate: 0.78,
      rollRate: 0.9,
      yawRate: 0.72,
      liftFactor: 0.82,
      stability: 0.74,
      autoLevelStrength: 3.4,
    },
    camera: { chaseDistance: 15, chaseHeight: 5, lookAhead: 9, fov: 58 },
  },
  {
    id: 'spitfire',
    name: 'Spitfire',
    era: 'ww2',
    displayRole: 'speed',
    handlingLabel: 'Fast ace run',
    difficulty: 'standard',
    available: true,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/british_spitfire_low_poly/scene.gltf',
    orientationPreset: 'gltf-x-forward',
    scale: 5.0,
    modelRotationY: Math.PI / 2,
    propellerBlur: { offset: [0, 0, -7.1], radius: 2.35, axis: 'z', color: 0xfff7d1, opacity: 0.28 },
    tuning: {
      minSpeed: 30,
      maxSpeed: 180,
      acceleration: 50,
      drag: 0.6,
      pitchRate: 1.0,
      rollRate: 1.5,
      yawRate: 0.5,
      liftFactor: 0.65,
      stability: 0.7,
      autoLevelStrength: 3.0,
    },
    camera: { chaseDistance: 16, chaseHeight: 6, lookAhead: 12, fov: 62 },
  },
  {
    id: 'cessna',
    name: 'Cessna 172',
    era: 'modern',
    displayRole: 'exploration',
    handlingLabel: 'Unavailable asset',
    difficulty: 'standard',
    available: false,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/cessna_172/scene.gltf',
    scale: 0.012,
    modelRotationY: 0,
    tuning: {
      minSpeed: 20,
      maxSpeed: 130,
      acceleration: 30,
      drag: 0.7,
      pitchRate: 0.9,
      rollRate: 1.3,
      yawRate: 0.45,
      liftFactor: 0.65,
      stability: 0.6,
      autoLevelStrength: 2.5,
    },
    camera: { chaseDistance: 16, chaseHeight: 5, lookAhead: 8, fov: 60 },
  },
  {
    id: 'celera',
    name: 'Celera 500L',
    era: 'experimental',
    displayRole: 'speed',
    handlingLabel: 'Unavailable asset',
    difficulty: 'ace',
    available: false,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/celera_500l/scene.gltf',
    scale: 5.0,
    modelRotationY: 0,
    tuning: {
      minSpeed: 30,
      maxSpeed: 200,
      acceleration: 55,
      drag: 0.35,
      pitchRate: 1.1,
      rollRate: 1.6,
      yawRate: 0.6,
      liftFactor: 0.55,
      stability: 0.7,
      autoLevelStrength: 2.5,
    },
    camera: { chaseDistance: 15, chaseHeight: 5, lookAhead: 12, fov: 65 },
  },
  {
    id: 'il28',
    name: 'IL-28 Reconnaissance',
    era: 'coldwar',
    displayRole: 'speed',
    handlingLabel: 'Heavy recon',
    difficulty: 'ace',
    available: true,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/il-28_soviet_reconnaissance_aircraft/scene.gltf',
    orientationPreset: 'gltf-recon-level',
    scale: 1,
    targetVisualSize: 20,
    cameraSafeRadius: 18,
    modelRotationY: Math.PI,
    modelRotationX: 0,
    modelRotationZ: 0,
    tuning: {
      minSpeed: 35,
      maxSpeed: 240,
      acceleration: 45,
      drag: 0.45,
      pitchRate: 0.9,
      rollRate: 1.1,
      yawRate: 0.4,
      liftFactor: 0.5,
      stability: 0.65,
      autoLevelStrength: 2.5,
    },
    camera: { chaseDistance: 22, chaseHeight: 7, lookAhead: 12, fov: 63 },
  },
  {
    id: 'ufo',
    name: 'Blue UFO',
    era: 'scifi',
    displayRole: 'novelty',
    handlingLabel: 'Unavailable asset',
    difficulty: 'ace',
    available: false,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/blue_ufo/scene.gltf',
    scale: 0.15,
    modelRotationY: 0,
    tuning: {
      minSpeed: 10,
      maxSpeed: 280,
      acceleration: 80,
      drag: 0.25,
      pitchRate: 1.6,
      rollRate: 2.0,
      yawRate: 1.2,
      liftFactor: 0.35,
      stability: 0.9,
      autoLevelStrength: 3.5,
    },
    camera: { chaseDistance: 12, chaseHeight: 4, lookAhead: 14, fov: 68 },
  },
  {
    id: 'scifi_plane',
    name: 'Sci-Fi Plane',
    era: 'scifi',
    displayRole: 'novelty',
    handlingLabel: 'Unavailable asset',
    difficulty: 'ace',
    available: false,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/sci-fi_plane_i_made_for_a_render/scene.gltf',
    scale: 0.35,
    modelRotationY: 0,
    tuning: {
      minSpeed: 40,
      maxSpeed: 260,
      acceleration: 60,
      drag: 0.35,
      pitchRate: 1.3,
      rollRate: 1.8,
      yawRate: 0.8,
      liftFactor: 0.45,
      stability: 0.8,
      autoLevelStrength: 3.0,
    },
    camera: { chaseDistance: 16, chaseHeight: 5, lookAhead: 12, fov: 66 },
  },
  {
    id: 'boeing737',
    name: 'Boeing 737-200',
    era: 'modern',
    displayRole: 'dev',
    handlingLabel: 'Unavailable asset',
    difficulty: 'ace',
    available: false,
    modelFormat: 'gltf',
    modelPath: '/assets/aircraft/boeing_737-200_white/scene.gltf',
    scale: 0.06,
    modelRotationY: 0,
    tuning: {
      minSpeed: 50,
      maxSpeed: 220,
      acceleration: 35,
      drag: 0.5,
      pitchRate: 0.6,
      rollRate: 0.8,
      yawRate: 0.3,
      liftFactor: 0.6,
      stability: 0.75,
      autoLevelStrength: 2.8,
    },
    camera: { chaseDistance: 35, chaseHeight: 12, lookAhead: 18, fov: 58 },
  },
];

export function getAvailableAircraft(): AircraftDefinition[] {
  return AIRCRAFT.filter((a) => a.available === true);
}

export function getAircraft(id: string): AircraftDefinition {
  return (
    AIRCRAFT.find((a) => a.id === id && a.available !== false) ??
    AIRCRAFT.find((a) => a.id === DEFAULT_AIRCRAFT_ID) ??
    AIRCRAFT[0]
  );
}

export function getNextAircraftId(currentId: string): string {
  const available = getAvailableAircraft();
  const idx = available.findIndex((a) => a.id === currentId);
  return available[(idx + 1) % available.length].id;
}

export function getPrevAircraftId(currentId: string): string {
  const available = getAvailableAircraft();
  const idx = available.findIndex((a) => a.id === currentId);
  return available[(idx - 1 + available.length) % available.length].id;
}
