import type { MapDefinition } from '@/game/types.ts';

export const MAPS: MapDefinition[] = [
  {
    id: 'desert_expanse',
    name: 'Desert Expanse',
    description: 'Vast sunbaked desert dotted with mesas, ruins, and outposts. Fly low and fast.',
    environmentPresetId: 'nevada',
    playerSpawn: [0, 150, 500],
    scatterLayers: [
      { type: 'rock', count: 250, radius: 8000, minDistance: 50, scaleRange: [6, 30] },
      { type: 'cactus', count: 100, radius: 7000, minDistance: 35, scaleRange: [5, 16] },
      { type: 'building', count: 18, radius: 5000, minDistance: 300, scaleRange: [8, 20] },
      { type: 'tower', count: 8, radius: 5000, minDistance: 500, scaleRange: [10, 18] },
      { type: 'mesa', count: 10, radius: 7000, minDistance: 700, scaleRange: [35, 80] },
      { type: 'sand_dune', count: 40, radius: 8000, minDistance: 250, scaleRange: [18, 45] },
      { type: 'ruins', count: 6, radius: 5000, minDistance: 600, scaleRange: [10, 20] },
      { type: 'wreck', count: 5, radius: 6000, minDistance: 700, scaleRange: [6, 12] },
    ],
    groundPlane: {
      color: 0xc8a96e,
      size: 22000,
    },
    skyObjectLayers: [
      {
        assetPath: '/assets/sky/objects/hot-air-balloon-01.glb',
        count: 3,
        radius: 7600,
        minDistance: 2800,
        altitudeRange: [650, 1450],
        scaleRange: [120, 220],
        driftSpeedRange: [2, 7],
        rotationSpeedRange: [-0.02, 0.02],
      },
      {
        assetPath: '/assets/sky/objects/blimp-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5600,
        altitudeRange: [1300, 2400],
        scaleRange: [280, 440],
        driftSpeedRange: [5, 12],
        rotationSpeedRange: [-0.01, 0.01],
      },
      {
        assetPath: '/assets/sky/objects/cloud-01.glb',
        count: 8,
        radius: 7600,
        minDistance: 1800,
        altitudeRange: [820, 2200],
        scaleRange: [260, 620],
        driftSpeedRange: [3, 9],
        rotationSpeedRange: [-0.008, 0.008],
      },
      {
        assetPath: '/assets/sky/objects/floating-island-02.glb',
        count: 2,
        radius: 9600,
        minDistance: 6200,
        altitudeRange: [700, 1250],
        scaleRange: [180, 340],
        driftSpeedRange: [1, 4],
        rotationSpeedRange: [-0.015, 0.015],
      },
      {
        assetPath: '/assets/sky/objects/kite-01.glb',
        count: 5,
        radius: 5200,
        minDistance: 800,
        altitudeRange: [280, 850],
        scaleRange: [45, 90],
        driftSpeedRange: [6, 14],
        rotationSpeedRange: [-0.08, 0.08],
      },
    ],
    atmosphere: {
      radius: 7000,
      hazeTexturePath: '/assets/sky/vfx/smoke-01.png',
      hazeCount: 6,
      hazeColor: 0xffd8a8,
      hazeOpacityRange: [0.008, 0.02],
      hazeScaleRange: [80, 180],
      hazeAltitudeRange: [700, 1900],
      hazeDriftSpeed: 10,
      rainTexturePath: '/assets/sky/vfx/rain-streak.png',
      rainCount: 0,
      rainColor: 0xffffff,
      rainOpacityRange: [0, 0],
      rainScaleRange: [1, 1],
      rainAltitudeRange: [0, 0],
      rainFallSpeed: 0,
      rainDriftSpeed: 0,
      lightning: false,
      lightningTexturePath: '/assets/sky/vfx/light-01.png',
      lightningColor: 0xffe1b0,
    },
    worldLandmarkLayers: [
      {
        assetPath: '/assets/world/desert-ruined-temple-01.glb',
        count: 1,
        radius: 7800,
        minDistance: 3600,
        altitudeRange: [0, 0],
        scaleRange: [560, 760],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-temple-02.glb',
        count: 1,
        radius: 7200,
        minDistance: 3400,
        altitudeRange: [0, 0],
        scaleRange: [420, 620],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-arch-01.glb',
        count: 2,
        radius: 7600,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [320, 560],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-canyon-01.glb',
        count: 1,
        radius: 9200,
        minDistance: 5200,
        altitudeRange: [0, 0],
        scaleRange: [1150, 1700],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-mesa-valley-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5600,
        altitudeRange: [0, 0],
        scaleRange: [1200, 1750],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-radar-01.glb',
        count: 1,
        radius: 7000,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [240, 340],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-radio-tower-01.glb',
        count: 1,
        radius: 7600,
        minDistance: 3400,
        altitudeRange: [0, 0],
        scaleRange: [300, 430],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/floating-islands-large-01.glb',
        count: 2,
        radius: 9600,
        minDistance: 5600,
        altitudeRange: [620, 1260],
        scaleRange: [360, 680],
        driftSpeedRange: [0.8, 2.4],
        rotationSpeedRange: [-0.01, 0.01],
      },
    ],
    weatherIdentity: {
      billboardLayers: [
        {
          texturePath: '/assets/weather/sand-smoke-01.png',
          count: 10,
          radius: 6400,
          altitudeRange: [70, 520],
          widthRange: [640, 1450],
          heightRange: [280, 720],
          opacityRange: [0.035, 0.075],
          color: 0xffc27d,
          driftSpeedRange: [10, 32],
          renderOrder: -3,
        },
        {
          texturePath: '/assets/weather/mist-puff-01.png',
          count: 8,
          radius: 7200,
          altitudeRange: [480, 1450],
          widthRange: [420, 980],
          heightRange: [220, 520],
          opacityRange: [0.02, 0.05],
          color: 0xffe5bd,
          driftSpeedRange: [8, 20],
          renderOrder: -4,
        },
      ],
      lightning: {
        texturePath: '/assets/weather/lightning-sheet-01.jpg',
        color: 0xffd9a3,
        distanceRange: [4300, 7600],
        altitudeRange: [900, 1850],
        scaleRange: [900, 1500],
        intervalRange: [10, 22],
        intensity: 5,
      },
    },
    combatVfx: {
      muzzleTexturePath: '/assets/vfx/muzzle-flash-01.png',
      hitTexturePath: '/assets/vfx/hit-puff-01.png',
      explosionTexturePath: '/assets/vfx/explosion-puff-01.png',
      smokeTexturePath: '/assets/vfx/smoke-trail-01.png',
      tracerColor: 0xffdf79,
      aiTracerColor: 0xff6060,
    },
    audioPolish: {
      ambientLoops: [
        { path: '/assets/audio/engine-low-01.ogg', volume: 0.018 },
        { path: '/assets/audio/thruster-fire-01.ogg', volume: 0.012 },
      ],
      weaponOneShots: [
        { path: '/assets/audio/laser-small-01.ogg', volume: 0.08, rateRange: [0.9, 1.08] },
        { path: '/assets/audio/laser-large-01.ogg', volume: 0.055, rateRange: [0.92, 1.02] },
      ],
      impactOneShots: [{ path: '/assets/audio/impact-metal-01.ogg', volume: 0.09, rateRange: [0.88, 1.08] }],
      explosionOneShots: [{ path: '/assets/audio/explosion-crunch-01.ogg', volume: 0.12, rateRange: [0.86, 1.02] }],
      uiOneShots: [{ path: '/assets/audio/radio-switch-01.ogg', volume: 0.05 }],
    },
    ringBehavior: 'aheadPath',
  },
  {
    id: 'ocean_islands',
    name: 'Ocean Islands',
    description: 'Tropical archipelago with boats, lighthouses, and marine life. Circle the islands and explore.',
    environmentPresetId: 'clearSky',
    playerSpawn: [0, 250, 400],
    scatterLayers: [
      { type: 'rock', count: 45, radius: 7000, minDistance: 100, scaleRange: [15, 50] },
      { type: 'palm_tree', count: 65, radius: 6000, minDistance: 28, scaleRange: [7, 18] },
      { type: 'pine_tree', count: 45, radius: 6000, minDistance: 32, scaleRange: [9, 22] },
      { type: 'sailboat', count: 18, radius: 7000, minDistance: 250, scaleRange: [4, 10] },
      { type: 'cargo_ship', count: 5, radius: 8000, minDistance: 900, scaleRange: [14, 22] },
      { type: 'whale', count: 6, radius: 7000, minDistance: 600, scaleRange: [10, 18] },
      { type: 'buoy', count: 20, radius: 7000, minDistance: 180, scaleRange: [3, 6] },
      { type: 'lighthouse', count: 4, radius: 5000, minDistance: 1200, scaleRange: [12, 16] },
    ],
    groundPlane: {
      color: 0x1478aa,
      size: 22000,
      opacity: 1.0,
      emissive: 0x0a5580,
      emissiveIntensity: 0.3,
    },
    skyObjectLayers: [
      {
        assetPath: '/assets/sky/objects/hot-air-balloon-02.glb',
        count: 3,
        radius: 7600,
        minDistance: 2800,
        altitudeRange: [620, 1500],
        scaleRange: [120, 220],
        driftSpeedRange: [2, 7],
        rotationSpeedRange: [-0.02, 0.02],
      },
      {
        assetPath: '/assets/sky/objects/airship-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5800,
        altitudeRange: [1350, 2600],
        scaleRange: [280, 460],
        driftSpeedRange: [6, 13],
        rotationSpeedRange: [-0.012, 0.012],
      },
      {
        assetPath: '/assets/sky/objects/cloud-03.glb',
        count: 10,
        radius: 8200,
        minDistance: 1800,
        altitudeRange: [800, 2450],
        scaleRange: [240, 600],
        driftSpeedRange: [4, 10],
        rotationSpeedRange: [-0.01, 0.01],
      },
      {
        assetPath: '/assets/sky/objects/floating-island-03.glb',
        count: 2,
        radius: 9800,
        minDistance: 6500,
        altitudeRange: [720, 1300],
        scaleRange: [180, 360],
        driftSpeedRange: [1, 4],
        rotationSpeedRange: [-0.012, 0.012],
      },
      {
        assetPath: '/assets/sky/objects/bird-01.glb',
        count: 8,
        radius: 5200,
        minDistance: 1800,
        altitudeRange: [260, 900],
        scaleRange: [24, 52],
        driftSpeedRange: [12, 26],
        rotationSpeedRange: [-0.08, 0.08],
      },
    ],
    atmosphere: {
      radius: 7200,
      hazeTexturePath: '/assets/sky/vfx/smoke-03.png',
      hazeCount: 6,
      hazeColor: 0xc8f1ff,
      hazeOpacityRange: [0.008, 0.02],
      hazeScaleRange: [80, 180],
      hazeAltitudeRange: [620, 1700],
      hazeDriftSpeed: 12,
      rainTexturePath: '/assets/sky/vfx/rain-streak.png',
      rainCount: 32,
      rainColor: 0xd8f5ff,
      rainOpacityRange: [0.06, 0.16],
      rainScaleRange: [20, 55],
      rainAltitudeRange: [320, 1300],
      rainFallSpeed: 120,
      rainDriftSpeed: 36,
      lightning: true,
      lightningTexturePath: '/assets/sky/vfx/light-01.png',
      lightningColor: 0xe8f9ff,
    },
    worldLandmarkLayers: [
      {
        assetPath: '/assets/world/ocean-lighthouse-01.glb',
        count: 2,
        radius: 7200,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [250, 360],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/ocean-port-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5200,
        altitudeRange: [0, 0],
        scaleRange: [900, 1350],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/ocean-seaport-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5400,
        altitudeRange: [0, 0],
        scaleRange: [1050, 1500],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/ocean-shipwreck-01.glb',
        count: 1,
        radius: 7400,
        minDistance: 3200,
        altitudeRange: [0, 0],
        scaleRange: [360, 620],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/ocean-cruise-ship-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5000,
        altitudeRange: [0, 0],
        scaleRange: [650, 1000],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/ocean-docks-03.glb',
        count: 1,
        radius: 7800,
        minDistance: 3600,
        altitudeRange: [0, 0],
        scaleRange: [520, 780],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/floating-islands-large-01.glb',
        count: 2,
        radius: 9800,
        minDistance: 6200,
        altitudeRange: [720, 1400],
        scaleRange: [340, 660],
        driftSpeedRange: [0.8, 2.2],
        rotationSpeedRange: [-0.01, 0.01],
      },
      {
        assetPath: '/assets/world/traffic-seaplane-01.glb',
        count: 2,
        radius: 8200,
        minDistance: 2600,
        altitudeRange: [420, 980],
        scaleRange: [90, 160],
        driftSpeedRange: [18, 34],
        rotationSpeedRange: [-0.02, 0.02],
        faceCenter: true,
      },
      {
        assetPath: '/assets/world/traffic-glider-01.glb',
        count: 2,
        radius: 7600,
        minDistance: 2400,
        altitudeRange: [760, 1600],
        scaleRange: [70, 130],
        driftSpeedRange: [10, 24],
        rotationSpeedRange: [-0.025, 0.025],
      },
      {
        assetPath: '/assets/world/traffic-seagull-01.glb',
        count: 6,
        radius: 5200,
        minDistance: 1500,
        altitudeRange: [240, 820],
        scaleRange: [38, 82],
        driftSpeedRange: [14, 30],
        rotationSpeedRange: [-0.05, 0.05],
      },
    ],
    weatherIdentity: {
      billboardLayers: [
        {
          texturePath: '/assets/weather/mist-puff-01.png',
          count: 12,
          radius: 6600,
          altitudeRange: [80, 680],
          widthRange: [420, 1150],
          heightRange: [220, 520],
          opacityRange: [0.035, 0.075],
          color: 0xd9f7ff,
          driftSpeedRange: [12, 28],
          renderOrder: -3,
        },
        {
          texturePath: '/assets/weather/storm-smoke-01.png',
          count: 7,
          radius: 7600,
          altitudeRange: [880, 1900],
          widthRange: [850, 1780],
          heightRange: [480, 920],
          opacityRange: [0.04, 0.09],
          color: 0x8fb6c4,
          driftSpeedRange: [10, 26],
          renderOrder: -4,
        },
        {
          texturePath: '/assets/sky/vfx/rain-streak.png',
          count: 42,
          radius: 3600,
          altitudeRange: [260, 1250],
          widthRange: [18, 46],
          heightRange: [120, 260],
          opacityRange: [0.07, 0.18],
          color: 0xd8f6ff,
          driftSpeedRange: [16, 42],
          fallSpeedRange: [110, 180],
          rotationRange: [-0.28, -0.16],
          renderOrder: -1,
        },
      ],
      lightning: {
        texturePath: '/assets/weather/lightning-sheet-01.jpg',
        color: 0xdff7ff,
        distanceRange: [3600, 6800],
        altitudeRange: [900, 2100],
        scaleRange: [900, 1600],
        intervalRange: [6, 14],
        intensity: 8,
      },
    },
    combatVfx: {
      muzzleTexturePath: '/assets/vfx/muzzle-flash-01.png',
      hitTexturePath: '/assets/vfx/hit-puff-01.png',
      explosionTexturePath: '/assets/vfx/explosion-puff-01.png',
      smokeTexturePath: '/assets/vfx/smoke-trail-01.png',
      tracerColor: 0xffe48b,
      aiTracerColor: 0xff6d7b,
    },
    audioPolish: {
      ambientLoops: [
        { path: '/assets/audio/engine-low-01.ogg', volume: 0.016 },
        { path: '/assets/audio/thruster-fire-01.ogg', volume: 0.012 },
      ],
      weaponOneShots: [
        { path: '/assets/audio/laser-small-01.ogg', volume: 0.08, rateRange: [0.9, 1.08] },
        { path: '/assets/audio/laser-large-01.ogg', volume: 0.055, rateRange: [0.92, 1.02] },
      ],
      impactOneShots: [{ path: '/assets/audio/impact-metal-01.ogg', volume: 0.09, rateRange: [0.88, 1.08] }],
      explosionOneShots: [{ path: '/assets/audio/explosion-crunch-01.ogg', volume: 0.12, rateRange: [0.86, 1.02] }],
      uiOneShots: [{ path: '/assets/audio/radio-switch-01.ogg', volume: 0.05 }],
    },
    ringBehavior: 'arena',
  },
];

export function getMap(id: string): MapDefinition {
  return MAPS.find((m) => m.id === id) ?? MAPS[0];
}
