import type { MapDefinition } from '@/game/types.ts';

export const MAPS: MapDefinition[] = [
  {
    id: 'desert_expanse',
    name: 'Sunspire Mesa',
    description: 'A warm ruin route of mesas, arch gates, radar towers, and drifting sky islands.',
    storyName: 'Sunspire Mesa',
    storyTagline: 'Ruins, radar beacons, and floating stones over a golden desert.',
    storyDescription:
      'The old Sunspire route crosses a buried temple, a canyon gate, and a lonely radar station that still blinks at dusk.',
    missionRoutes: {
      zen: [
        {
          id: 'desert-zen-arch',
          label: 'Arch Gate',
          description: 'Ease through the first sunlit stone gate.',
          kind: 'ring',
          position: [160, 210, -420],
          radius: 48,
          score: 120,
          color: 0xffd36b,
        },
        {
          id: 'desert-zen-temple',
          label: 'Temple Turn',
          description: 'Bank gently around the buried temple roofline.',
          kind: 'ring',
          position: [-520, 260, -1180],
          radius: 52,
          score: 140,
          color: 0xffe0a3,
        },
        {
          id: 'desert-zen-canyon',
          label: 'Canyon Breath',
          description: 'Hold a steady line across the canyon wall.',
          kind: 'ring',
          position: [760, 330, -2020],
          radius: 58,
          score: 160,
          color: 0xfbbf24,
        },
        {
          id: 'desert-zen-island',
          label: 'Floating Stone',
          description: 'Climb toward the slow-moving island silhouette.',
          kind: 'ring',
          position: [260, 620, -2860],
          radius: 64,
          score: 180,
          color: 0xfff1b8,
        },
        {
          id: 'desert-zen-radar',
          label: 'Radar Glow',
          description: 'Let the radar beacon guide the final curve.',
          kind: 'ring',
          position: [-700, 420, -3620],
          radius: 56,
          score: 180,
          color: 0xfcd34d,
        },
        {
          id: 'desert-zen-return',
          label: 'Mesa Return',
          description: 'Return to the open mesa air lane.',
          kind: 'ring',
          position: [120, 260, -4480],
          radius: 60,
          score: 200,
          color: 0xffc27d,
        },
      ],
      expedition: [
        {
          id: 'desert-exp-temple',
          label: 'Wake the Temple Beacon',
          description: 'Reach the temple marker and circle its warm light.',
          kind: 'landmark',
          position: [-660, 150, -1280],
          radius: 180,
          score: 350,
          color: 0xffd166,
        },
        {
          id: 'desert-exp-low-arch',
          label: 'Low Pass Through the Arch',
          description: 'Drop below the high haze and pass the canyon arch.',
          kind: 'low_pass',
          position: [980, 120, -2140],
          radius: 170,
          score: 425,
          color: 0xf97316,
        },
        {
          id: 'desert-exp-sky-island',
          label: 'Sky Island Postcard',
          description: 'Climb to the floating island for a postcard view.',
          kind: 'postcard',
          position: [320, 760, -3000],
          radius: 220,
          score: 475,
          color: 0xfef3c7,
        },
        {
          id: 'desert-exp-radar',
          label: 'Tune the Radar Tower',
          description: 'Find the blinking tower beyond the sand curtain.',
          kind: 'landmark',
          position: [-920, 270, -3820],
          radius: 210,
          score: 525,
          color: 0x93c5fd,
        },
        {
          id: 'desert-exp-canyon-wall',
          label: 'Trace the Mesa Wall',
          description: 'Follow the broad canyon silhouette at cruising altitude.',
          kind: 'climb',
          position: [1120, 520, -4860],
          radius: 260,
          score: 575,
          color: 0xf59e0b,
        },
      ],
      dogfight: [
        {
          id: 'desert-dogfight-arch',
          label: 'Arch Tag Lane',
          description: 'Keep the rival framed near the stone gate.',
          kind: 'combat_anchor',
          position: [600, 360, -1500],
          radius: 420,
          score: 0,
          color: 0xfb7185,
        },
        {
          id: 'desert-dogfight-radar',
          label: 'Radar Ribbon Turn',
          description: 'Use the tower as a visual anchor during turns.',
          kind: 'combat_anchor',
          position: [-920, 420, -3600],
          radius: 520,
          score: 0,
          color: 0xfca5a5,
        },
      ],
    },
    environmentPresetId: 'nevada',
    playerSpawn: [0, 90, 500],
    scatterLayers: [
      {
        type: 'rock',
        count: 250,
        radius: 8000,
        minDistance: 50,
        scaleRange: [6, 30],
        collision: { radiusMultiplier: 0.85, minScale: 22, label: 'mesa rock' },
      },
      { type: 'cactus', count: 100, radius: 7000, minDistance: 35, scaleRange: [5, 16] },
      {
        type: 'building',
        count: 18,
        radius: 5000,
        minDistance: 300,
        scaleRange: [8, 20],
        collision: { radiusMultiplier: 1.45, minScale: 10, label: 'building' },
      },
      {
        type: 'tower',
        count: 8,
        radius: 5000,
        minDistance: 500,
        scaleRange: [10, 18],
        collision: { radiusMultiplier: 1.2, minScale: 10, label: 'radar tower' },
      },
      {
        type: 'mesa',
        count: 10,
        radius: 7000,
        minDistance: 700,
        scaleRange: [35, 80],
        collision: { radiusMultiplier: 1.1, minScale: 35, label: 'mesa' },
      },
      { type: 'sand_dune', count: 40, radius: 8000, minDistance: 250, scaleRange: [18, 45] },
      {
        type: 'ruins',
        count: 6,
        radius: 5000,
        minDistance: 600,
        scaleRange: [10, 20],
        collision: { radiusMultiplier: 1.25, minScale: 12, label: 'ruins' },
      },
      {
        type: 'wreck',
        count: 5,
        radius: 6000,
        minDistance: 700,
        scaleRange: [6, 12],
        collision: { radiusMultiplier: 1.1, minScale: 8, label: 'wreck' },
      },
    ],
    groundPlane: {
      color: 0xd3a65f,
      size: 22000,
      emissive: 0x9d6c2d,
      emissiveIntensity: 0.28,
    },
    skyObjectLayers: [
      {
        assetPath: '/assets/sky/objects/hot-air-balloon-01.glb',
        count: 3,
        radius: 7600,
        minDistance: 2800,
        altitudeRange: [650, 1450],
        scaleRange: [120, 220],
        behavior: 'balloon',
        orientationPreset: 'balloon-z-up',
        maintainUpright: true,
        faceVelocity: false,
        bobAmplitude: 20,
        driftSpeedRange: [2, 7],
        rotationSpeedRange: [-0.02, 0.02],
      },
      {
        assetPath: '/assets/sky/objects/blimp-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5600,
        altitudeRange: [1300, 2400],
        scaleRange: [280, 440],
        behavior: 'airship',
        orientationPreset: 'native',
        faceVelocity: true,
        bobAmplitude: 8,
        driftSpeedRange: [5, 12],
        rotationSpeedRange: [-0.01, 0.01],
      },
      {
        assetPath: '/assets/sky/objects/cloud-01.glb',
        count: 8,
        radius: 7600,
        minDistance: 1800,
        altitudeRange: [820, 2200],
        scaleRange: [260, 620],
        behavior: 'cloud',
        bobAmplitude: 5,
        driftSpeedRange: [3, 9],
        rotationSpeedRange: [-0.008, 0.008],
      },
      {
        assetPath: '/assets/sky/objects/floating-island-02.glb',
        count: 2,
        radius: 9600,
        minDistance: 6200,
        altitudeRange: [700, 1250],
        scaleRange: [180, 340],
        behavior: 'floating-island',
        bobAmplitude: 4,
        driftSpeedRange: [1, 4],
        rotationSpeedRange: [-0.015, 0.015],
      },
      {
        assetPath: '/assets/sky/objects/kite-01.glb',
        count: 5,
        radius: 5200,
        minDistance: 800,
        altitudeRange: [280, 850],
        scaleRange: [45, 90],
        behavior: 'traffic',
        orientationPreset: 'native',
        faceVelocity: true,
        bobAmplitude: 12,
        driftSpeedRange: [6, 14],
        rotationSpeedRange: [-0.08, 0.08],
      },
    ],
    atmosphere: {
      radius: 7000,
      hazeTexturePath: '/assets/sky/vfx/smoke-01.png',
      hazeCount: 6,
      hazeColor: 0xffd8a8,
      hazeOpacityRange: [0.008, 0.02],
      hazeScaleRange: [80, 180],
      hazeAltitudeRange: [700, 1900],
      hazeDriftSpeed: 10,
      rainTexturePath: '/assets/sky/vfx/rain-streak.png',
      rainCount: 0,
      rainColor: 0xffffff,
      rainOpacityRange: [0, 0],
      rainScaleRange: [1, 1],
      rainAltitudeRange: [0, 0],
      rainFallSpeed: 0,
      rainDriftSpeed: 0,
      lightning: false,
      lightningTexturePath: '/assets/sky/vfx/light-01.png',
      lightningColor: 0xffe1b0,
    },
    worldLandmarkLayers: [
      {
        label: 'pyramid',
        assetPath: '/assets/world/desert-pyramid-01.glb',
        count: 1,
        radius: 7600,
        minDistance: 4200,
        altitudeRange: [0, 0],
        scaleRange: [720, 980],
        groundY: 0,
        collisionRadius: 260,
        placements: [{ position: [-660, 0, -1280], targetSize: 920, rotationY: 0.4, collisionRadius: 280 }],
      },
      {
        label: 'ruined temple',
        assetPath: '/assets/world/desert-ruined-temple-01.glb',
        count: 1,
        radius: 7800,
        minDistance: 3600,
        altitudeRange: [0, 0],
        scaleRange: [560, 760],
        groundY: 0,
        collisionRadius: 210,
        placements: [{ position: [-420, 0, -1550], targetSize: 680, rotationY: -0.2, collisionRadius: 220 }],
      },
      {
        label: 'temple',
        assetPath: '/assets/world/desert-temple-02.glb',
        count: 1,
        radius: 7200,
        minDistance: 3400,
        altitudeRange: [0, 0],
        scaleRange: [420, 620],
        groundY: 0,
        collisionRadius: 170,
        placements: [{ position: [120, 0, -780], targetSize: 520, rotationY: 0.12, collisionRadius: 185 }],
      },
      {
        label: 'stone arch',
        assetPath: '/assets/world/desert-arch-01.glb',
        count: 2,
        radius: 7600,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [320, 560],
        groundY: 0,
        collisionRadius: 150,
        placements: [
          { position: [980, 0, -2140], targetSize: 540, rotationY: 0.35, collisionRadius: 155 },
          { position: [430, 0, -560], targetSize: 420, rotationY: -0.6, collisionRadius: 130 },
        ],
      },
      {
        assetPath: '/assets/world/desert-canyon-01.glb',
        count: 1,
        radius: 9200,
        minDistance: 5200,
        altitudeRange: [0, 0],
        scaleRange: [1150, 1700],
        groundY: 0,
      },
      {
        assetPath: '/assets/world/desert-mesa-valley-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5600,
        altitudeRange: [0, 0],
        scaleRange: [1200, 1750],
        groundY: 0,
      },
      {
        label: 'radar tower',
        assetPath: '/assets/world/desert-radar-01.glb',
        count: 1,
        radius: 7000,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [240, 340],
        groundY: 0,
        collisionRadius: 120,
        placements: [{ position: [-920, 0, -3820], targetSize: 320, rotationY: 0.8, collisionRadius: 125 }],
      },
      {
        label: 'radio tower',
        assetPath: '/assets/world/desert-radio-tower-01.glb',
        count: 1,
        radius: 7600,
        minDistance: 3400,
        altitudeRange: [0, 0],
        scaleRange: [300, 430],
        groundY: 0,
        collisionRadius: 115,
        placements: [{ position: [-1350, 0, -4300], targetSize: 390, rotationY: -0.3, collisionRadius: 120 }],
      },
      {
        label: 'floating island',
        assetPath: '/assets/world/floating-islands-large-01.glb',
        count: 2,
        radius: 9600,
        minDistance: 5600,
        altitudeRange: [620, 1260],
        scaleRange: [360, 680],
        driftSpeedRange: [0.8, 2.4],
        rotationSpeedRange: [-0.01, 0.01],
        collisionRadius: 250,
        placements: [
          { position: [320, 760, -3000], targetSize: 620, rotationY: 0.2, collisionRadius: 270 },
          { position: [1120, 920, -4860], targetSize: 560, rotationY: -0.5, collisionRadius: 240 },
        ],
      },
    ],
    livingWorld: {
      seed: 24031,
      eventIntervalRange: [8, 17],
      events: [
        {
          id: 'desert-balloon-hover',
          label: 'balloon drift',
          assetPath: '/assets/sky/objects/hot-air-balloon-03.glb',
          behavior: 'balloon-hover',
          weight: 3.8,
          maxActive: 3,
          countRange: [1, 1],
          radiusRange: [1800, 5200],
          altitudeRange: [520, 1450],
          scaleRange: [130, 230],
          orientationPreset: 'balloon-upright',
          maintainUpright: true,
          faceVelocity: false,
          speedRange: [2, 7],
          durationRange: [42, 78],
        },
        {
          id: 'desert-glider-pass',
          label: 'sun glider pass',
          assetPath: '/assets/world/traffic-glider-01.glb',
          behavior: 'plane-pass',
          weight: 2.6,
          maxActive: 2,
          countRange: [1, 1],
          radiusRange: [2200, 5600],
          altitudeRange: [540, 1350],
          scaleRange: [72, 130],
          orientationPreset: 'native',
          faceVelocity: true,
          speedRange: [70, 130],
          durationRange: [24, 42],
        },
        {
          id: 'desert-parachute-drift',
          label: 'expedition parachute',
          assetPath: '/assets/world/traffic-parachute-01.glb',
          behavior: 'kite-drift',
          weight: 1.4,
          maxActive: 2,
          countRange: [1, 1],
          radiusRange: [1600, 4400],
          altitudeRange: [360, 1100],
          scaleRange: [48, 90],
          orientationPreset: 'native',
          maintainUpright: true,
          faceVelocity: false,
          speedRange: [5, 14],
          durationRange: [36, 70],
        },
        {
          id: 'desert-ufo-dart',
          label: 'strange silver flash',
          assetPath: '/assets/sky/objects/ufo-saucer-01.glb',
          behavior: 'ufo-dart',
          weight: 0.42,
          chance: 0.72,
          maxActive: 1,
          countRange: [1, 2],
          radiusRange: [2400, 6200],
          altitudeRange: [680, 1750],
          scaleRange: [95, 165],
          orientationPreset: 'native',
          faceVelocity: true,
          speedRange: [260, 420],
          durationRange: [6, 12],
        },
      ],
    },
    weatherIdentity: {
      billboardLayers: [
        {
          texturePath: '/assets/weather/sand-smoke-01.png',
          count: 10,
          radius: 6400,
          altitudeRange: [70, 520],
          widthRange: [640, 1450],
          heightRange: [280, 720],
          opacityRange: [0.035, 0.075],
          color: 0xffc27d,
          driftSpeedRange: [10, 32],
          renderOrder: -3,
        },
        {
          texturePath: '/assets/weather/mist-puff-01.png',
          count: 8,
          radius: 7200,
          altitudeRange: [480, 1450],
          widthRange: [420, 980],
          heightRange: [220, 520],
          opacityRange: [0.02, 0.05],
          color: 0xffe5bd,
          driftSpeedRange: [8, 20],
          renderOrder: -4,
        },
      ],
      lightning: {
        texturePath: '/assets/weather/lightning-sheet-01.jpg',
        color: 0xffd9a3,
        distanceRange: [4300, 7600],
        altitudeRange: [900, 1850],
        scaleRange: [900, 1500],
        intervalRange: [10, 22],
        intensity: 5,
      },
    },
    combatVfx: {
      muzzleTexturePath: '/assets/vfx/muzzle-flash-01.png',
      hitTexturePath: '/assets/vfx/hit-puff-01.png',
      explosionTexturePath: '/assets/vfx/explosion-puff-01.png',
      smokeTexturePath: '/assets/vfx/smoke-trail-01.png',
      tracerColor: 0xffdf79,
      aiTracerColor: 0xff6060,
    },
    audioPolish: {
      ambientLoops: [
        { path: '/assets/audio/engine-low-01.ogg', volume: 0.018 },
        { path: '/assets/audio/thruster-fire-01.ogg', volume: 0.012 },
      ],
      weaponOneShots: [
        { path: '/assets/audio/laser-small-01.ogg', volume: 0.04, rateRange: [1.02, 1.16] },
        { path: '/assets/audio/laser-large-01.ogg', volume: 0.03, rateRange: [1.02, 1.12] },
      ],
      impactOneShots: [{ path: '/assets/audio/impact-metal-01.ogg', volume: 0.04, rateRange: [1.02, 1.18] }],
      explosionOneShots: [{ path: '/assets/audio/explosion-crunch-01.ogg', volume: 0.055, rateRange: [1.08, 1.22] }],
      uiOneShots: [{ path: '/assets/audio/radio-switch-01.ogg', volume: 0.05 }],
    },
    ringBehavior: 'aheadPath',
  },
  {
    id: 'ocean_islands',
    name: 'Stormglass Archipelago',
    description: 'A lighthouse and harbor route with mist lanes, shipwrecks, storm banks, and airships.',
    storyName: 'Stormglass Archipelago',
    storyTagline: 'Lighthouses, harbor lights, rain squalls, and wide blue sky lanes.',
    storyDescription:
      'Stormglass is a chain of bright islands where lighthouse crews, airships, and seaplanes share the same weather-beaten sky.',
    missionRoutes: {
      zen: [
        {
          id: 'ocean-zen-lighthouse',
          label: 'Lighthouse Arc',
          description: 'Roll into the route beside the lighthouse beam.',
          kind: 'ring',
          position: [220, 260, -460],
          radius: 52,
          score: 120,
          color: 0xbff4ff,
        },
        {
          id: 'ocean-zen-harbor',
          label: 'Harbor Drift',
          description: 'Hold a wide, smooth line over the docks.',
          kind: 'ring',
          position: [-620, 310, -1220],
          radius: 58,
          score: 145,
          color: 0x7dd3fc,
        },
        {
          id: 'ocean-zen-rain',
          label: 'Mist Lane',
          description: 'Thread the soft mist curtains without rushing.',
          kind: 'ring',
          position: [740, 420, -2020],
          radius: 62,
          score: 165,
          color: 0x93c5fd,
        },
        {
          id: 'ocean-zen-airship',
          label: 'Airship Wake',
          description: 'Climb toward the airship traffic lane.',
          kind: 'ring',
          position: [160, 760, -2900],
          radius: 68,
          score: 185,
          color: 0xe0f2fe,
        },
        {
          id: 'ocean-zen-shipwreck',
          label: 'Shipwreck Turn',
          description: 'Curve back over the old wreck marker.',
          kind: 'ring',
          position: [-760, 360, -3720],
          radius: 60,
          score: 190,
          color: 0xbae6fd,
        },
        {
          id: 'ocean-zen-horizon',
          label: 'Open Horizon',
          description: 'Finish the loop in clean air above the islands.',
          kind: 'ring',
          position: [260, 430, -4540],
          radius: 64,
          score: 210,
          color: 0xf0f9ff,
        },
      ],
      expedition: [
        {
          id: 'ocean-exp-lighthouse',
          label: 'Light the Keeper Route',
          description: 'Reach the lighthouse and pick up its route beacon.',
          kind: 'landmark',
          position: [420, 180, -760],
          radius: 190,
          score: 350,
          color: 0xfef08a,
        },
        {
          id: 'ocean-exp-docks',
          label: 'Harbor Low Pass',
          description: 'Skim the harbor lane just above the dock lights.',
          kind: 'low_pass',
          position: [-820, 130, -1580],
          radius: 180,
          score: 430,
          color: 0x38bdf8,
        },
        {
          id: 'ocean-exp-stormbank',
          label: 'Storm Bank Climb',
          description: 'Climb through the mist to read the storm shelf.',
          kind: 'climb',
          position: [980, 820, -2520],
          radius: 250,
          score: 500,
          color: 0xc4b5fd,
        },
        {
          id: 'ocean-exp-airship',
          label: 'Airship Postcard',
          description: 'Find the airship lane and hold it in view.',
          kind: 'postcard',
          position: [120, 1080, -3440],
          radius: 260,
          score: 540,
          color: 0xdbeafe,
        },
        {
          id: 'ocean-exp-shipwreck',
          label: 'Mark the Shipwreck',
          description: 'Circle the wreck marker on the way back to harbor.',
          kind: 'landmark',
          position: [-980, 260, -4380],
          radius: 240,
          score: 580,
          color: 0x67e8f9,
        },
      ],
      dogfight: [
        {
          id: 'ocean-dogfight-lighthouse',
          label: 'Lighthouse Tag Loop',
          description: 'Use the lighthouse beam to orient the chase.',
          kind: 'combat_anchor',
          position: [520, 420, -1200],
          radius: 480,
          score: 0,
          color: 0xfda4af,
        },
        {
          id: 'ocean-dogfight-storm',
          label: 'Storm Shelf',
          description: 'Watch the rival against the rain bank silhouette.',
          kind: 'combat_anchor',
          position: [-780, 760, -3300],
          radius: 620,
          score: 0,
          color: 0xfb7185,
        },
      ],
    },
    environmentPresetId: 'tropical',
    playerSpawn: [0, 110, 400],
    scatterLayers: [
      {
        type: 'rock',
        count: 45,
        radius: 7000,
        minDistance: 100,
        scaleRange: [15, 50],
        collision: { radiusMultiplier: 0.9, minScale: 28, label: 'island rock' },
      },
      { type: 'palm_tree', count: 42, radius: 6200, minDistance: 220, scaleRange: [20, 44] },
      { type: 'sailboat', count: 18, radius: 7000, minDistance: 250, scaleRange: [4, 10] },
      {
        type: 'cargo_ship',
        count: 5,
        radius: 8000,
        minDistance: 900,
        scaleRange: [14, 22],
        collision: { radiusMultiplier: 1.7, minScale: 14, label: 'cargo ship' },
      },
      { type: 'whale', count: 6, radius: 7000, minDistance: 600, scaleRange: [10, 18] },
      { type: 'buoy', count: 20, radius: 7000, minDistance: 180, scaleRange: [3, 6] },
      {
        type: 'lighthouse',
        count: 4,
        radius: 5000,
        minDistance: 1200,
        scaleRange: [12, 16],
        collision: { radiusMultiplier: 1.45, minScale: 12, label: 'lighthouse island' },
      },
    ],
    groundPlane: {
      color: 0x0f8ec4,
      size: 22000,
      opacity: 1.0,
      emissive: 0x0a78a8,
      emissiveIntensity: 0.55,
    },
    skyObjectLayers: [
      {
        assetPath: '/assets/sky/objects/hot-air-balloon-02.glb',
        count: 3,
        radius: 7600,
        minDistance: 2800,
        altitudeRange: [620, 1500],
        scaleRange: [120, 220],
        behavior: 'balloon',
        orientationPreset: 'balloon-upright',
        maintainUpright: true,
        faceVelocity: false,
        bobAmplitude: 20,
        driftSpeedRange: [2, 7],
        rotationSpeedRange: [-0.02, 0.02],
      },
      {
        assetPath: '/assets/sky/objects/airship-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5800,
        altitudeRange: [1350, 2600],
        scaleRange: [280, 460],
        behavior: 'airship',
        orientationPreset: 'native',
        faceVelocity: true,
        bobAmplitude: 8,
        driftSpeedRange: [6, 13],
        rotationSpeedRange: [-0.012, 0.012],
      },
      {
        assetPath: '/assets/sky/objects/cloud-03.glb',
        count: 10,
        radius: 8200,
        minDistance: 1800,
        altitudeRange: [800, 2450],
        scaleRange: [240, 600],
        behavior: 'cloud',
        bobAmplitude: 5,
        driftSpeedRange: [4, 10],
        rotationSpeedRange: [-0.01, 0.01],
      },
      {
        assetPath: '/assets/sky/objects/floating-island-03.glb',
        count: 2,
        radius: 9800,
        minDistance: 6500,
        altitudeRange: [720, 1300],
        scaleRange: [180, 360],
        behavior: 'floating-island',
        bobAmplitude: 4,
        driftSpeedRange: [1, 4],
        rotationSpeedRange: [-0.012, 0.012],
      },
      {
        assetPath: '/assets/sky/objects/bird-01.glb',
        count: 8,
        radius: 5200,
        minDistance: 1800,
        altitudeRange: [260, 900],
        scaleRange: [24, 52],
        behavior: 'bird',
        orientationPreset: 'native',
        faceVelocity: true,
        bobAmplitude: 8,
        driftSpeedRange: [12, 26],
        rotationSpeedRange: [-0.08, 0.08],
      },
    ],
    livingWorld: {
      seed: 50621,
      eventIntervalRange: [7, 16],
      events: [
        {
          id: 'ocean-seaplane-pass',
          label: 'seaplane lane',
          assetPath: '/assets/world/traffic-seaplane-01.glb',
          behavior: 'plane-pass',
          weight: 3.2,
          maxActive: 3,
          countRange: [1, 2],
          radiusRange: [1800, 5400],
          altitudeRange: [380, 980],
          scaleRange: [92, 160],
          orientationPreset: 'native',
          faceVelocity: true,
          speedRange: [70, 135],
          durationRange: [24, 45],
        },
        {
          id: 'ocean-airship-pass',
          label: 'airship crossing',
          assetPath: '/assets/sky/objects/blimp-02.glb',
          behavior: 'airship-pass',
          weight: 2.4,
          maxActive: 2,
          countRange: [1, 1],
          radiusRange: [2600, 6600],
          altitudeRange: [900, 1900],
          scaleRange: [220, 380],
          orientationPreset: 'x-forward',
          faceVelocity: true,
          speedRange: [18, 42],
          durationRange: [38, 76],
        },
        {
          id: 'ocean-seagull-pass',
          label: 'harbor birds',
          assetPath: '/assets/world/traffic-seagull-01.glb',
          behavior: 'bird-pass',
          weight: 2.2,
          maxActive: 4,
          countRange: [2, 5],
          radiusRange: [1100, 3600],
          altitudeRange: [180, 720],
          scaleRange: [34, 72],
          orientationPreset: 'native',
          faceVelocity: true,
          speedRange: [50, 95],
          durationRange: [15, 30],
        },
        {
          id: 'ocean-balloon-hover',
          label: 'festival balloon',
          assetPath: '/assets/sky/objects/hot-air-balloon-02.glb',
          behavior: 'balloon-hover',
          weight: 1.7,
          maxActive: 2,
          countRange: [1, 1],
          radiusRange: [1800, 5200],
          altitudeRange: [560, 1400],
          scaleRange: [125, 220],
          orientationPreset: 'balloon-upright',
          maintainUpright: true,
          faceVelocity: false,
          speedRange: [2, 7],
          durationRange: [42, 78],
        },
        {
          id: 'ocean-ufo-dart',
          label: 'stormlight saucer',
          assetPath: '/assets/sky/objects/ufo-saucer-01.glb',
          behavior: 'ufo-dart',
          weight: 0.36,
          chance: 0.68,
          maxActive: 1,
          countRange: [1, 2],
          radiusRange: [2600, 6800],
          altitudeRange: [760, 1850],
          scaleRange: [95, 170],
          orientationPreset: 'native',
          faceVelocity: true,
          speedRange: [270, 430],
          durationRange: [6, 12],
        },
      ],
    },
    atmosphere: {
      radius: 7200,
      hazeTexturePath: '/assets/sky/vfx/smoke-03.png',
      hazeCount: 6,
      hazeColor: 0xc8f1ff,
      hazeOpacityRange: [0.008, 0.02],
      hazeScaleRange: [80, 180],
      hazeAltitudeRange: [620, 1700],
      hazeDriftSpeed: 12,
      rainTexturePath: '/assets/sky/vfx/rain-streak.png',
      rainCount: 0,
      rainColor: 0xd8f5ff,
      rainOpacityRange: [0.06, 0.16],
      rainScaleRange: [20, 55],
      rainAltitudeRange: [320, 1300],
      rainFallSpeed: 120,
      rainDriftSpeed: 36,
      lightning: true,
      lightningTexturePath: '/assets/sky/vfx/light-01.png',
      lightningColor: 0xe8f9ff,
    },
    worldLandmarkLayers: [
      {
        label: 'lighthouse',
        assetPath: '/assets/world/ocean-lighthouse-01.glb',
        count: 2,
        radius: 7200,
        minDistance: 3000,
        altitudeRange: [0, 0],
        scaleRange: [250, 360],
        groundY: 0,
        collisionRadius: 130,
        islandBase: { radius: 260, height: 18, color: 0xe1c891, flatten: 0.76 },
        placements: [
          {
            position: [420, 0, -760],
            targetSize: 340,
            rotationY: 0.35,
            collisionRadius: 140,
            islandBase: { radius: 300, height: 18, color: 0xe5cc94, flatten: 0.78 },
          },
          {
            position: [1180, 0, -2920],
            targetSize: 300,
            rotationY: -0.2,
            collisionRadius: 130,
            islandBase: { radius: 250, height: 16, color: 0xdcc38c, flatten: 0.7 },
          },
        ],
      },
      {
        label: 'harbor island',
        assetPath: '/assets/world/ocean-port-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5200,
        altitudeRange: [0, 0],
        scaleRange: [900, 1350],
        groundY: 0,
        islandBase: { radius: 620, height: 22, color: 0xd6bd84, flatten: 0.68 },
        placements: [
          {
            position: [-820, 0, -1580],
            targetSize: 1180,
            rotationY: -0.45,
            islandBase: { radius: 700, height: 24, color: 0xd9bd80, flatten: 0.66 },
          },
        ],
      },
      {
        label: 'seaport island',
        assetPath: '/assets/world/ocean-seaport-01.glb',
        count: 1,
        radius: 9400,
        minDistance: 5400,
        altitudeRange: [0, 0],
        scaleRange: [1050, 1500],
        groundY: 0,
        islandBase: { radius: 720, height: 24, color: 0xd4b77a, flatten: 0.66 },
      },
      {
        label: 'shipwreck',
        assetPath: '/assets/world/ocean-shipwreck-01.glb',
        count: 1,
        radius: 7400,
        minDistance: 3200,
        altitudeRange: [0, 0],
        scaleRange: [360, 620],
        groundY: 0,
        collisionRadius: 190,
        islandBase: { radius: 420, height: 14, color: 0xcab07d, flatten: 0.6 },
        placements: [
          {
            position: [-980, 0, -4380],
            targetSize: 560,
            rotationY: 0.7,
            collisionRadius: 200,
            islandBase: { radius: 460, height: 14, color: 0xc7ad78, flatten: 0.62 },
          },
        ],
      },
      {
        label: 'cruise ship',
        assetPath: '/assets/world/ocean-cruise-ship-01.glb',
        count: 1,
        radius: 9000,
        minDistance: 5000,
        altitudeRange: [0, 0],
        scaleRange: [650, 1000],
        groundY: 0,
        collisionRadius: 260,
        islandBase: { radius: 520, height: 16, color: 0xcbb382, flatten: 0.58 },
      },
      {
        label: 'dock island',
        assetPath: '/assets/world/ocean-docks-03.glb',
        count: 1,
        radius: 7800,
        minDistance: 3600,
        altitudeRange: [0, 0],
        scaleRange: [520, 780],
        groundY: 0,
        islandBase: { radius: 460, height: 16, color: 0xd8bf87, flatten: 0.7 },
        placements: [
          {
            position: [-520, 0, -1080],
            targetSize: 640,
            rotationY: 0.28,
            islandBase: { radius: 500, height: 16, color: 0xdac28c, flatten: 0.72 },
          },
        ],
      },
      {
        label: 'floating island',
        assetPath: '/assets/world/floating-islands-large-01.glb',
        count: 2,
        radius: 9800,
        minDistance: 6200,
        altitudeRange: [720, 1400],
        scaleRange: [340, 660],
        driftSpeedRange: [0.8, 2.2],
        rotationSpeedRange: [-0.01, 0.01],
        collisionRadius: 260,
      },
      {
        assetPath: '/assets/world/traffic-seaplane-01.glb',
        count: 2,
        radius: 8200,
        minDistance: 2600,
        altitudeRange: [420, 980],
        scaleRange: [90, 160],
        driftSpeedRange: [18, 34],
        rotationSpeedRange: [-0.02, 0.02],
        faceCenter: true,
      },
      {
        assetPath: '/assets/world/traffic-glider-01.glb',
        count: 2,
        radius: 7600,
        minDistance: 2400,
        altitudeRange: [760, 1600],
        scaleRange: [70, 130],
        driftSpeedRange: [10, 24],
        rotationSpeedRange: [-0.025, 0.025],
      },
      {
        assetPath: '/assets/world/traffic-seagull-01.glb',
        count: 6,
        radius: 5200,
        minDistance: 1500,
        altitudeRange: [240, 820],
        scaleRange: [38, 82],
        driftSpeedRange: [14, 30],
        rotationSpeedRange: [-0.05, 0.05],
      },
    ],
    weatherIdentity: {
      billboardLayers: [
        {
          texturePath: '/assets/weather/mist-puff-01.png',
          count: 12,
          radius: 6600,
          altitudeRange: [80, 680],
          widthRange: [420, 1150],
          heightRange: [220, 520],
          opacityRange: [0.035, 0.075],
          color: 0xd9f7ff,
          driftSpeedRange: [12, 28],
          renderOrder: -3,
        },
        {
          texturePath: '/assets/weather/storm-smoke-01.png',
          count: 7,
          radius: 7600,
          altitudeRange: [880, 1900],
          widthRange: [850, 1780],
          heightRange: [480, 920],
          opacityRange: [0.04, 0.09],
          color: 0x8fb6c4,
          driftSpeedRange: [10, 26],
          renderOrder: -4,
        },
        {
          texturePath: '/assets/weather/storm-smoke-01.png',
          count: 6,
          radius: 6200,
          altitudeRange: [360, 1350],
          widthRange: [760, 1540],
          heightRange: [720, 1420],
          opacityRange: [0.028, 0.055],
          color: 0xd8f6ff,
          driftSpeedRange: [16, 42],
          rotationRange: [-0.08, 0.08],
          renderOrder: -4,
        },
      ],
      lightning: {
        texturePath: '/assets/weather/lightning-sheet-01.jpg',
        color: 0xdff7ff,
        distanceRange: [4800, 7800],
        altitudeRange: [900, 2100],
        scaleRange: [900, 1600],
        intervalRange: [14, 28],
        intensity: 4.5,
      },
    },
    combatVfx: {
      muzzleTexturePath: '/assets/vfx/muzzle-flash-01.png',
      hitTexturePath: '/assets/vfx/hit-puff-01.png',
      explosionTexturePath: '/assets/vfx/explosion-puff-01.png',
      smokeTexturePath: '/assets/vfx/smoke-trail-01.png',
      tracerColor: 0xffe48b,
      aiTracerColor: 0xff6d7b,
    },
    audioPolish: {
      ambientLoops: [
        { path: '/assets/audio/engine-low-01.ogg', volume: 0.016 },
        { path: '/assets/audio/thruster-fire-01.ogg', volume: 0.012 },
      ],
      weaponOneShots: [
        { path: '/assets/audio/laser-small-01.ogg', volume: 0.04, rateRange: [1.02, 1.16] },
        { path: '/assets/audio/laser-large-01.ogg', volume: 0.03, rateRange: [1.02, 1.12] },
      ],
      impactOneShots: [{ path: '/assets/audio/impact-metal-01.ogg', volume: 0.04, rateRange: [1.02, 1.18] }],
      explosionOneShots: [{ path: '/assets/audio/explosion-crunch-01.ogg', volume: 0.055, rateRange: [1.08, 1.22] }],
      uiOneShots: [{ path: '/assets/audio/radio-switch-01.ogg', volume: 0.05 }],
    },
    ringBehavior: 'arena',
  },
];

export function getMap(id: string): MapDefinition {
  return MAPS.find((m) => m.id === id) ?? MAPS[0];
}
